# Generated by Django 2.1.8 on 2019-10-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverylist',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='deliverylist',
            name='notion',
        ),
    ]
