# Generated by Django 2.1.8 on 2019-10-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20191001_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylist',
            name='menu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverylist',
            name='notion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='deliverylist',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='deliverylist',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
