# Generated by Django 2.1.8 on 2019-10-06 10:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20191006_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverylist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='deliverylist',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='deliverylist',
            name='notion',
        ),
        migrations.AddField(
            model_name='deliverylist',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
