# Generated by Django 2.1.8 on 2019-10-06 10:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_auto_20191006_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverylist',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
