# Generated by Django 2.1.8 on 2019-09-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0002_auto_20190925_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageboard',
            name='likes',
        ),
        migrations.AddField(
            model_name='imageboard',
            name='like_posts',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='imageboard.ImageBoard'),
        ),
    ]
