# Generated by Django 2.1.8 on 2019-09-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0007_remove_imageboard_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageboard',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
