# Generated by Django 2.1.8 on 2019-09-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0009_remove_imageboard_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageboard',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
