# Generated by Django 2.1.8 on 2019-09-21 16:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190922_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
