# Generated by Django 2.1.8 on 2019-09-21 16:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20190922_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
