# Generated by Django 2.1.8 on 2019-09-21 17:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20190922_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
