# Generated by Django 2.1.8 on 2019-09-21 18:04

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20190922_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
