# Generated by Django 2.1.8 on 2019-09-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_auto_20190929_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeboard',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
