# Generated by Django 2.1.8 on 2019-10-10 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='document',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
